# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    - /refs/heads/*
    - !master

name: Test-env-deployment

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Authorize and deploy app
        env:
          APPNAME: PlacidoProjectTestEnv
          ACCOUNT: dleo
          SERVER: shinyapps.io
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        run: |
          rsconnect::setAccountInfo(name='dleo', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))
          rsconnect::deployApp('.', appName = 'PlacidoProject', launch.browser = FALSE)
        shell: Rscript {0}
