name: Deploy PlacidoApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.2.3'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R dependencies
      run: |
        install.packages("remotes")
        install.packages("rsconnect")
        remotes::install_deps(dependencies = TRUE)

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e "rsconnect::setAccountInfo(name='dleo', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        Rscript -e "rsconnect::deployApp('.', appName = 'PlacidoProject', launch.browser = FALSE)"
